const {
  Document, Packer, Paragraph, TextRun, Table, TableRow, TableCell,
  HeadingLevel, AlignmentType, BorderStyle, WidthType, ShadingType,
  TableOfContents, PageBreak, LevelFormat
} = require('docx');
const fs = require('fs');

// ─── Helpers ────────────────────────────────────────────────────────────────
const BORDER = { style: BorderStyle.SINGLE, size: 1, color: 'D1D5DB' };
const BORDERS = { top: BORDER, bottom: BORDER, left: BORDER, right: BORDER };
const NO_BORDER = { style: BorderStyle.NONE, size: 0, color: 'FFFFFF' };
const NO_BORDERS = { top: NO_BORDER, bottom: NO_BORDER, left: NO_BORDER, right: NO_BORDER };
const CELL_MARGIN = { top: 100, bottom: 100, left: 140, right: 140 };

function heading1(text) {
  return new Paragraph({
    heading: HeadingLevel.HEADING_1,
    spacing: { before: 360, after: 120 },
    children: [new TextRun({ text, bold: true, size: 32, font: 'Arial', color: '1E1B4B' })],
  });
}
function heading2(text) {
  return new Paragraph({
    heading: HeadingLevel.HEADING_2,
    spacing: { before: 280, after: 80 },
    children: [new TextRun({ text, bold: true, size: 26, font: 'Arial', color: '312E81' })],
  });
}
function heading3(text) {
  return new Paragraph({
    heading: HeadingLevel.HEADING_3,
    spacing: { before: 200, after: 60 },
    children: [new TextRun({ text, bold: true, size: 22, font: 'Arial', color: '4F46E5' })],
  });
}
function para(text, opts = {}) {
  return new Paragraph({
    spacing: { before: 60, after: 80 },
    children: [new TextRun({ text, size: 20, font: 'Arial', color: '374151', ...opts })],
  });
}
function codePara(text) {
  return new Paragraph({
    spacing: { before: 40, after: 40 },
    indent: { left: 360 },
    children: [new TextRun({ text, size: 18, font: 'Courier New', color: '1F2937' })],
  });
}
function bullet(text, indent = 0) {
  return new Paragraph({
    numbering: { reference: 'bullets', level: indent },
    spacing: { before: 40, after: 40 },
    children: [new TextRun({ text, size: 20, font: 'Arial', color: '374151' })],
  });
}
function numbered(text, indent = 0) {
  return new Paragraph({
    numbering: { reference: 'numbers', level: indent },
    spacing: { before: 40, after: 40 },
    children: [new TextRun({ text, size: 20, font: 'Arial', color: '374151' })],
  });
}
function rule() {
  return new Paragraph({
    spacing: { before: 160, after: 160 },
    border: { bottom: { style: BorderStyle.SINGLE, size: 4, color: 'E5E7EB', space: 1 } },
    children: [],
  });
}
function emptyLine() {
  return new Paragraph({ spacing: { before: 40, after: 40 }, children: [] });
}
function badge(text, color = '6366F1') {
  return new TextRun({ text: ` ${text} `, bold: true, size: 18, font: 'Arial', color: 'FFFFFF',
    highlight: undefined, shading: { fill: color } });
}

function makeTable(headers, rows, colWidths) {
  const total = colWidths.reduce((a, b) => a + b, 0);
  return new Table({
    width: { size: total, type: WidthType.DXA },
    columnWidths: colWidths,
    rows: [
      new TableRow({
        tableHeader: true,
        children: headers.map((h, i) => new TableCell({
          borders: BORDERS,
          width: { size: colWidths[i], type: WidthType.DXA },
          shading: { fill: '4338CA', type: ShadingType.CLEAR },
          margins: CELL_MARGIN,
          children: [new Paragraph({ children: [new TextRun({ text: h, bold: true, size: 18, font: 'Arial', color: 'FFFFFF' })] })],
        })),
      }),
      ...rows.map((row, ri) => new TableRow({
        children: row.map((cell, i) => new TableCell({
          borders: BORDERS,
          width: { size: colWidths[i], type: WidthType.DXA },
          shading: { fill: ri % 2 === 0 ? 'F5F3FF' : 'FFFFFF', type: ShadingType.CLEAR },
          margins: CELL_MARGIN,
          children: [new Paragraph({ children: [new TextRun({ text: cell, size: 18, font: 'Arial', color: '1F2937' })] })],
        })),
      })),
    ],
  });
}

function codeBlock(lines) {
  return [
    new Paragraph({
      spacing: { before: 80, after: 0 },
      shading: { fill: 'F1F5F9', type: ShadingType.CLEAR },
      indent: { left: 240, right: 240 },
      border: {
        top: { style: BorderStyle.SINGLE, size: 2, color: 'CBD5E1' },
        left: { style: BorderStyle.SINGLE, size: 2, color: 'CBD5E1' },
        right: { style: BorderStyle.SINGLE, size: 2, color: 'CBD5E1' },
        bottom: lines.length === 1 ? { style: BorderStyle.SINGLE, size: 2, color: 'CBD5E1' } : BorderStyle.NONE,
      },
      children: [new TextRun({ text: lines[0], size: 17, font: 'Courier New', color: '1E40AF' })],
    }),
    ...lines.slice(1).map((line, idx) => new Paragraph({
      spacing: { before: 0, after: idx === lines.length - 2 ? 80 : 0 },
      shading: { fill: 'F1F5F9', type: ShadingType.CLEAR },
      indent: { left: 240, right: 240 },
      border: {
        left: { style: BorderStyle.SINGLE, size: 2, color: 'CBD5E1' },
        right: { style: BorderStyle.SINGLE, size: 2, color: 'CBD5E1' },
        bottom: idx === lines.length - 2 ? { style: BorderStyle.SINGLE, size: 2, color: 'CBD5E1' } : undefined,
      },
      children: [new TextRun({ text: line, size: 17, font: 'Courier New', color: '1E40AF' })],
    })),
  ];
}

// ─── DOCUMENT ───────────────────────────────────────────────────────────────
const children = [

  // ── COVER ──────────────────────────────────────────────────────────────────
  new Paragraph({
    spacing: { before: 480, after: 120 },
    alignment: AlignmentType.CENTER,
    children: [new TextRun({ text: '🧠 Pulse-Learn AI', size: 52, bold: true, font: 'Arial', color: '1E1B4B' })],
  }),
  new Paragraph({
    alignment: AlignmentType.CENTER,
    spacing: { before: 60, after: 60 },
    children: [new TextRun({ text: 'Product Requirement Document — Version 4.0', size: 28, font: 'Arial', color: '4F46E5' })],
  }),
  new Paragraph({
    alignment: AlignmentType.CENTER,
    spacing: { before: 40, after: 40 },
    children: [new TextRun({ text: 'Loop-Style Components · Notion AI Layer · MCP Bridge · Page Hierarchy · Workflow Automation', size: 20, font: 'Arial', color: '6B7280', italics: true })],
  }),
  new Paragraph({
    alignment: AlignmentType.CENTER,
    spacing: { before: 40, after: 320 },
    children: [new TextRun({ text: 'Builds on v3.0 (MBTI Engine · Block Workspace · Auth · Analytics · Blockchain)', size: 18, font: 'Arial', color: '9CA3AF' })],
  }),
  rule(),

  // ── SECTION 1: WHAT'S NEW ──────────────────────────────────────────────────
  heading1('1. What Changed in v4 — The Upgrade Map'),
  para('v4 absorbs two powerful paradigms: Microsoft Loop\'s shareable live components and Notion AI\'s integrated intelligence layer. The result is a Learning OS where every block can be shared across workspaces, every page has a hierarchy, and an AI assistant lives natively inside the canvas — not as a separate chat tab.'),
  emptyLine(),
  makeTable(
    ['Dimension', 'v3', 'v4'],
    [
      ['Workspace model', 'Single flat block canvas per roadmap', 'Hierarchical pages + subpages inside each workspace (Loop-style)'],
      ['Block sharing', 'Blocks exist only in one workspace', 'Loop Components — any block can be detached and shared as a live embed across multiple pages'],
      ['AI interaction', 'AI operates at route level (quiz, roadmap gen)', 'Native in-canvas AI assistant (Notion AI style) — highlight text, / command, or sidebar chat'],
      ['External tools', 'No external integrations', 'MCP Bridge layer — connect Google Calendar, GitHub, Slack, Notion, Figma'],
      ['Cross-workspace search', 'None', 'Unified search across all pages, blocks, and nodes (Notion-style global search)'],
      ['Workspace templates', 'No templates', 'Save any workspace layout as a reusable team template'],
      ['AI Recap', 'Not present', 'One-click AI-generated summary of any page or workspace (Loop Recap feature)'],
      ['Workflow automation', 'Manual only', 'Trigger-based automations: e.g. "When node completed → notify Slack → update GitHub issue"'],
    ],
    [2400, 3000, 3960]
  ),
  emptyLine(),
  rule(),

  // ── SECTION 2: NEW FEATURE OVERVIEW ───────────────────────────────────────
  heading1('2. New Feature Overview — v4 Features at a Glance'),

  heading2('2.1 Feature D: Loop Components (Live Shareable Blocks)'),
  para('Inspired directly by Microsoft Loop\'s "Share Loop component" feature. In v3, a Quiz Block existed only inside the workspace where it was created. In v4, any block can be detached and turned into a Loop Component — a live, synced widget that can be embedded in any other workspace page, or shared as a standalone link.'),
  emptyLine(),
  bullet('Any block can be "detached" to become a standalone Loop Component with its own UUID'),
  bullet('A Loop Component renders identically wherever it is embedded — same live data'),
  bullet('Edits to the component (e.g. quiz answers, notes) sync to all embed locations in real time via Supabase Realtime'),
  bullet('"Share component link" generates a public or team-scoped shareable URL'),
  bullet('"Add to workspace" copies the component embed into another page'),
  emptyLine(),

  heading2('2.2 Feature E: Page Hierarchy (Nested Pages)'),
  para('Workspaces in v4 have a nested page structure, similar to Loop\'s sidebar hierarchy. Each roadmap workspace can have multiple pages and each page can have subpages, creating a structured learning environment rather than a single flat canvas.'),
  emptyLine(),
  bullet('Workspace → Pages → Subpages (3 levels deep, matching Loop\'s model)'),
  bullet('Sidebar navigation tree showing all pages and their nesting'),
  bullet('"New subpage" action on any page (matching the Loop context menu)'),
  bullet('Page titles are editable inline; pages support "Rename and style" theming'),
  bullet('"Open" action navigates to the page in full-screen view'),
  bullet('"Duplicate" page duplicates its block layout and all non-Loop-component blocks'),
  bullet('"Save page as template" stores the layout in the template library'),
  emptyLine(),

  heading2('2.3 Feature F: Native In-Canvas AI Assistant (Notion AI Style)'),
  para('In v3, AI interaction happened only at defined touchpoints: quiz generation, roadmap generation, analytics queries. In v4, an AI assistant lives natively inside the workspace canvas, accessible via slash command, text highlight, or a persistent sidebar chat — exactly as Notion AI operates.'),
  emptyLine(),
  bullet('Slash command (/ai) anywhere in the Notes block opens an inline AI prompt'),
  bullet('Select any text in any block → "Ask AI" floating tooltip appears'),
  bullet('AI sidebar chat panel: persistent collapsible chat that has full context of the current workspace page'),
  bullet('AI can read, summarize, and act on any block in the current page (read-only by default)'),
  bullet('AI can insert content into a Notes block on command: "Summarize Node 3 into a study note"'),
  bullet('All AI interactions are MBTI-context-aware — the same MBTI profile from v3 drives all AI responses'),
  emptyLine(),

  heading2('2.4 Feature G: AI Recap'),
  para('Directly ported from Microsoft Loop\'s "Recap" feature. One click on any page generates a structured AI summary of all activity, content, and progress on that page.'),
  emptyLine(),
  bullet('Recap covers: node completion activity, quiz scores, collaborator contributions, notes content'),
  bullet('Output is a structured summary block inserted at the top of the page'),
  bullet('MBTI-aware: Recap format adapts to the user\'s cognitive type (INTJ gets bullet-point executive summary; INFP gets narrative summary)'),
  bullet('Recap can be regenerated at any time'),
  emptyLine(),

  heading2('2.5 Feature H: MCP Bridge Layer (External Tool Integrations)'),
  para('Inspired by the Notion MCP Architecture diagram (Image 3). An MCP Bridge connects Pulse-Learn to external tools. External data flows through the MCP bridge into the workspace — adding it to blocks, nodes, or triggering actions.'),
  emptyLine(),
  bullet('Google Calendar: Import study schedule; sync node deadlines as calendar events'),
  bullet('GitHub: Link nodes to GitHub issues; mark node complete when issue is closed'),
  bullet('Slack: Post progress updates, quiz results, and completion events to a Slack channel'),
  bullet('Notion: Pull a Notion page as a Notes block or export a workspace Recap to Notion'),
  bullet('Figma: Embed a Figma design as a reference block within the workspace'),
  bullet('MCP connections are configured per-workspace in the Workspace Settings panel'),
  emptyLine(),

  heading2('2.6 Feature I: Workflow Automation'),
  para('Trigger-based automations between workspace events and MCP-connected tools. Users define simple if-then rules without code.'),
  emptyLine(),
  bullet('Trigger: "Node marked complete" → Action: "Post to Slack #learning channel"'),
  bullet('Trigger: "Quiz score < 60%" → Action: "Create GitHub issue: Review [Node Title]"'),
  bullet('Trigger: "Roadmap 100% complete" → Action: "Create calendar event: Exam Ready Day"'),
  bullet('Trigger: "New collaborator joins" → Action: "Send Slack DM with workspace link"'),
  bullet('Automations are defined via a visual rule builder (no-code) in Workspace Settings'),
  emptyLine(),

  heading2('2.7 Feature J: Global Search'),
  para('A unified search bar (Cmd+K / Ctrl+K) searches across all pages, blocks, nodes, notes, and collaborator comments in all workspaces the user has access to.'),
  emptyLine(),
  bullet('Indexes: page titles, node titles, notes content, quiz questions, collaborator names'),
  bullet('Results are categorized: Pages, Nodes, Notes, Quiz Questions, Comments'),
  bullet('Fuzzy matching — searches "docker net" and finds "Docker Networking Fundamentals"'),
  bullet('Recent searches are stored per user session'),
  emptyLine(),
  rule(),

  // ── SECTION 3: UPDATED FILE STRUCTURE ─────────────────────────────────────
  heading1('3. Updated Folder Structure — v4 New and Changed Files'),
  para('Only new (← NEW) and changed (← UPDATED) files are marked. All v3 files carry over unchanged.'),
  emptyLine(),
  ...codeBlock([
    'pulse-learn/',
    '├── client/src/',
    '│   ├── components/',
    '│   │   ├── workspace/',
    '│   │   │   ├── WorkspaceCanvas.jsx           ← UPDATED (page hierarchy + Loop component support)',
    '│   │   │   ├── BlockPalette.jsx              ← UPDATED (Loop Component block type added)',
    '│   │   │   ├── PageSidebar.jsx               ← NEW (nested page tree navigation)',
    '│   │   │   ├── PageBreadcrumb.jsx            ← NEW (current page path display)',
    '│   │   │   ├── WorkspaceSettings.jsx         ← NEW (MCP connections + automations config)',
    '│   │   │   ├── AIAssistantSidebar.jsx        ← NEW (Notion AI-style persistent chat)',
    '│   │   │   ├── RecapBlock.jsx                ← NEW (AI Recap output block)',
    '│   │   │   ├── LoopComponentViewer.jsx       ← NEW (shared component embed renderer)',
    '│   │   │   └── blocks/',
    '│   │   │       ├── SkillTreeBlock.jsx        (unchanged)',
    '│   │   │       ├── ChartBlock.jsx            (unchanged)',
    '│   │   │       ├── TableBlock.jsx            (unchanged)',
    '│   │   │       ├── QuizBlock.jsx             ← UPDATED (Loop component detach support)',
    '│   │   │       ├── NotesBlock.jsx            ← UPDATED (/ai slash command + highlight AI)',
    '│   │   │       ├── ProgressBlock.jsx         (unchanged)',
    '│   │   │       └── MBTIInsightBlock.jsx      (unchanged)',
    '│   │   ├── search/',
    '│   │   │   ├── GlobalSearch.jsx              ← NEW (Cmd+K search modal)',
    '│   │   │   └── SearchResults.jsx             ← NEW (categorized results display)',
    '│   │   └── automation/',
    '│   │       ├── AutomationRuleBuilder.jsx     ← NEW (visual no-code automation builder)',
    '│   │       └── MCPConnectionPanel.jsx        ← NEW (external tool connect/disconnect)',
    '│   ├── hooks/',
    '│   │   ├── useWorkspace.js                   ← UPDATED (page hierarchy state)',
    '│   │   ├── useLoopComponents.js              ← NEW (Loop component sync via Realtime)',
    '│   │   ├── useGlobalSearch.js                ← NEW (search index + query hook)',
    '│   │   ├── useAIAssistant.js                 ← NEW (in-canvas AI state management)',
    '│   │   └── useMCPBridge.js                   ← NEW (MCP connection state + actions)',
    '│   └── lib/',
    '│       ├── mbtiProfiles.js                   (unchanged)',
    '│       ├── blockTypes.js                     ← UPDATED (LOOP_COMPONENT type added)',
    '│       └── automationTriggers.js             ← NEW (trigger/action registry)',
    '',
    '├── server/',
    '│   ├── routes/',
    '│   │   ├── workspace.js                      ← UPDATED (page hierarchy endpoints)',
    '│   │   ├── loopComponent.js                  ← NEW (Loop component CRUD + share)',
    '│   │   ├── search.js                         ← NEW (full-text search endpoint)',
    '│   │   ├── recap.js                          ← NEW (AI Recap generation)',
    '│   │   ├── aiAssistant.js                    ← NEW (in-canvas AI chat endpoint)',
    '│   │   └── automation.js                     ← NEW (automation rules CRUD + execution)',
    '│   └── services/',
    '│       ├── geminiService.js                  ← UPDATED (recap + assistant prompts)',
    '│       ├── mcpBridgeService.js               ← NEW (MCP server orchestration)',
    '│       └── searchService.js                  ← NEW (Supabase full-text search logic)',
  ]),
  emptyLine(),
  rule(),

  // ── SECTION 4: DATABASE SCHEMA ─────────────────────────────────────────────
  heading1('4. Database Schema — v4 Additions'),
  para('Run this SQL in the Supabase editor. It adds 5 new tables on top of v3 schema. All v3 tables are unchanged.'),
  emptyLine(),

  heading2('4.1 Workspace Pages (Page Hierarchy)'),
  ...codeBlock([
    'CREATE TABLE workspace_pages (',
    '    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),',
    '    workspace_id UUID REFERENCES workspace_layouts(id) ON DELETE CASCADE,',
    '    roadmap_id UUID REFERENCES roadmaps(id) ON DELETE CASCADE,',
    '    user_id UUID REFERENCES users(id) ON DELETE CASCADE,',
    '    parent_page_id UUID REFERENCES workspace_pages(id) ON DELETE CASCADE,',
    '    title TEXT NOT NULL DEFAULT \'Untitled Page\',',
    '    icon TEXT DEFAULT \'📄\',',
    '    cover_color TEXT DEFAULT \'#4F46E5\',',
    '    layout_json JSONB NOT NULL DEFAULT \'[]\',',
    '    sequence_order INT DEFAULT 0,',
    '    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),',
    '    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()',
    ');',
    'ALTER TABLE workspace_pages ENABLE ROW LEVEL SECURITY;',
    'CREATE POLICY "Users manage own pages" ON workspace_pages',
    '  FOR ALL USING (auth.uid() = user_id);',
    'ALTER PUBLICATION supabase_realtime ADD TABLE workspace_pages;',
  ]),
  emptyLine(),

  heading2('4.2 Loop Components (Shareable Live Blocks)'),
  ...codeBlock([
    'CREATE TABLE loop_components (',
    '    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),',
    '    owner_user_id UUID REFERENCES users(id) ON DELETE CASCADE,',
    '    roadmap_id UUID REFERENCES roadmaps(id) ON DELETE CASCADE,',
    '    block_type TEXT NOT NULL,  -- SKILL_TREE | QUIZ | CHART | etc.',
    '    block_config JSONB NOT NULL DEFAULT \'{}\',',
    '    share_scope TEXT DEFAULT \'team\',  -- "team" | "public" | "private"',
    '    share_token TEXT UNIQUE,           -- URL-safe token for public sharing',
    '    title TEXT DEFAULT \'Shared Component\',',
    '    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),',
    '    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()',
    ');',
    '',
    '-- Tracks which pages a Loop Component is embedded in',
    'CREATE TABLE loop_component_embeds (',
    '    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),',
    '    component_id UUID REFERENCES loop_components(id) ON DELETE CASCADE,',
    '    page_id UUID REFERENCES workspace_pages(id) ON DELETE CASCADE,',
    '    position_in_layout JSONB,',
    '    UNIQUE(component_id, page_id)',
    ');',
    '',
    'ALTER TABLE loop_components ENABLE ROW LEVEL SECURITY;',
    'CREATE POLICY "Users manage own components" ON loop_components',
    '  FOR ALL USING (auth.uid() = owner_user_id);',
    'ALTER PUBLICATION supabase_realtime ADD TABLE loop_components;',
  ]),
  emptyLine(),

  heading2('4.3 MCP Connections & Automation Rules'),
  ...codeBlock([
    'CREATE TABLE mcp_connections (',
    '    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),',
    '    roadmap_id UUID REFERENCES roadmaps(id) ON DELETE CASCADE,',
    '    user_id UUID REFERENCES users(id) ON DELETE CASCADE,',
    '    service TEXT NOT NULL,  -- "google_calendar" | "github" | "slack" | "notion" | "figma"',
    '    connection_config JSONB NOT NULL DEFAULT \'{}\',  -- tokens, IDs, etc.',
    '    is_active BOOLEAN DEFAULT true,',
    '    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()',
    ');',
    '',
    'CREATE TABLE automation_rules (',
    '    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),',
    '    roadmap_id UUID REFERENCES roadmaps(id) ON DELETE CASCADE,',
    '    user_id UUID REFERENCES users(id) ON DELETE CASCADE,',
    '    trigger_type TEXT NOT NULL,',
    '    -- "node_completed" | "quiz_failed" | "roadmap_completed" | "collaborator_joined"',
    '    trigger_config JSONB DEFAULT \'{}\',',
    '    action_type TEXT NOT NULL,',
    '    -- "post_slack" | "create_github_issue" | "create_calendar_event" | "send_slack_dm"',
    '    action_config JSONB DEFAULT \'{}\',',
    '    is_active BOOLEAN DEFAULT true,',
    '    last_triggered_at TIMESTAMP WITH TIME ZONE',
    ');',
    '',
    'ALTER TABLE mcp_connections ENABLE ROW LEVEL SECURITY;',
    'ALTER TABLE automation_rules ENABLE ROW LEVEL SECURITY;',
    'CREATE POLICY "Users manage own connections" ON mcp_connections',
    '  FOR ALL USING (auth.uid() = user_id);',
    'CREATE POLICY "Users manage own automations" ON automation_rules',
    '  FOR ALL USING (auth.uid() = user_id);',
  ]),
  emptyLine(),
  rule(),

  // ── SECTION 5: FEATURE D — LOOP COMPONENTS ────────────────────────────────
  heading1('5. Feature D — Loop Components (Full Implementation)'),

  heading2('5.1 What a Loop Component Is'),
  para('A Loop Component is a block that has been "detached" from a specific page and given its own identity. It can be embedded in N pages simultaneously. All embeds show the same live data. If someone updates the block\'s underlying data, all embeds update.'),
  emptyLine(),

  heading2('5.2 useLoopComponents.js'),
  ...codeBlock([
    '// client/src/hooks/useLoopComponents.js',
    '// Copilot trigger: // Custom hook to create, fetch, embed, and sync Loop Components via Supabase Realtime',
    '',
    'import { useState, useEffect } from \'react\';',
    'import axios from \'axios\';',
    'import { supabase } from \'../lib/supabaseClient\';',
    '',
    'export function useLoopComponents(roadmapId, accessToken) {',
    '  const [components, setComponents] = useState([]);',
    '',
    '  useEffect(() => {',
    '    // Subscribe to real-time updates on loop_components',
    '    const channel = supabase',
    '      .channel(`loop-${roadmapId}`)',
    '      .on(\'postgres_changes\', {',
    '        event: \'UPDATE\', schema: \'public\', table: \'loop_components\',',
    '        filter: `roadmap_id=eq.${roadmapId}`,',
    '      }, (payload) => {',
    '        setComponents(prev => prev.map(c =>',
    '          c.id === payload.new.id ? { ...c, ...payload.new } : c',
    '        ));',
    '      })',
    '      .subscribe();',
    '    return () => supabase.removeChannel(channel);',
    '  }, [roadmapId]);',
    '',
    '  const detachBlock = async (block) => {',
    '    const { data } = await axios.post(',
    '      `${import.meta.env.VITE_API_URL}/api/loop-component`,',
    '      { roadmap_id: roadmapId, block_type: block.type, block_config: block.config, title: block.id },',
    '      { headers: { Authorization: `Bearer ${accessToken}` } }',
    '    );',
    '    setComponents(prev => [...prev, data.component]);',
    '    return data.component;',
    '  };',
    '',
    '  const getShareLink = (component) =>',
    '    `${window.location.origin}/shared/component/${component.share_token}`;',
    '',
    '  return { components, detachBlock, getShareLink };',
    '}',
  ]),
  emptyLine(),

  heading2('5.3 loopComponent Route (server/routes/loopComponent.js)'),
  ...codeBlock([
    '// POST /api/loop-component — detach a block as a Loop Component',
    '// GET  /api/loop-component/:id — fetch a component by ID',
    '// GET  /api/loop-component/shared/:token — public fetch (no auth)',
    '// PATCH /api/loop-component/:id — update component config',
    '',
    'router.post(\'/\', requireAuth, async (req, res) => {',
    '  const { roadmap_id, block_type, block_config, title } = req.body;',
    '  const share_token = crypto.randomUUID().replace(/-/g, \'\').slice(0, 16);',
    '  const { data, error } = await supabase.from(\'loop_components\').insert({',
    '    owner_user_id: req.user.id,',
    '    roadmap_id, block_type, block_config,',
    '    title, share_token, share_scope: \'team\',',
    '  }).select().single();',
    '  if (error) return res.status(500).json({ error: error.message });',
    '  res.json({ component: data });',
    '});',
    '',
    '// Public endpoint — no auth (share_scope = "public" only)',
    'router.get(\'/shared/:token\', async (req, res) => {',
    '  const { data } = await supabase.from(\'loop_components\')',
    '    .select(\'*\').eq(\'share_token\', req.params.token)',
    '    .eq(\'share_scope\', \'public\').single();',
    '  if (!data) return res.status(404).json({ error: \'Not found\' });',
    '  res.json({ component: data });',
    '});',
  ]),
  emptyLine(),

  heading2('5.4 Block Context Menu — "Share as Loop Component"'),
  para('Every block header in WorkspaceCanvas gets a "⋯" menu with these options (update the block header render in WorkspaceCanvas.jsx):'),
  emptyLine(),
  ...codeBlock([
    '// In WorkspaceCanvas.jsx block header, replace the ✕ button with a context menu',
    '// Copilot trigger: // Block header context menu with Share as Loop Component, Duplicate, Delete options',
    '',
    'const BlockContextMenu = ({ block, onDetach, onDuplicate, onRemove }) => (',
    '  <div className="relative group">',
    '    <button className="text-gray-600 hover:text-white text-xs px-2">⋯</button>',
    '    <div className="hidden group-hover:flex absolute right-0 top-6 z-50 bg-gray-800 border border-gray-700',
    '      rounded-xl shadow-2xl flex-col min-w-48 py-1">',
    '      <button onClick={() => onDetach(block)}',
    '        className="px-4 py-2 text-left text-sm text-gray-300 hover:text-white hover:bg-gray-700">',
    '        🔗 Share as Loop Component',
    '      </button>',
    '      <button onClick={() => onDuplicate(block)}',
    '        className="px-4 py-2 text-left text-sm text-gray-300 hover:text-white hover:bg-gray-700">',
    '        📋 Duplicate Block',
    '      </button>',
    '      <div className="border-t border-gray-700 my-1" />',
    '      <button onClick={() => onRemove(block.id)}',
    '        className="px-4 py-2 text-left text-sm text-red-400 hover:text-red-300 hover:bg-gray-700">',
    '        🗑 Remove from Page',
    '      </button>',
    '    </div>',
    '  </div>',
    ');',
  ]),
  emptyLine(),
  rule(),

  // ── SECTION 6: FEATURE E — PAGE HIERARCHY ─────────────────────────────────
  heading1('6. Feature E — Page Hierarchy (Nested Pages)'),

  heading2('6.1 PageSidebar Component'),
  ...codeBlock([
    '// client/src/components/workspace/PageSidebar.jsx',
    '// Copilot trigger: // Collapsible sidebar with nested page tree, drag to reorder,',
    '// new page / new subpage buttons, right-click context menu with rename/share/delete/template',
    '',
    'export default function PageSidebar({ pages, currentPageId, onPageSelect, onNewPage,',
    '  onNewSubpage, onRenamePage, onDeletePage, onSaveAsTemplate }) {',
    '',
    '  const renderPage = (page, depth = 0) => (',
    '    <div key={page.id} style={{ paddingLeft: `${depth * 16}px` }}>',
    '      <div',
    '        onClick={() => onPageSelect(page.id)}',
    '        className={`flex items-center gap-2 px-3 py-1.5 rounded-lg cursor-pointer text-sm',
    '          transition-colors group ${ currentPageId === page.id',
    '            ? \'bg-indigo-950 text-indigo-300\'',
    '            : \'text-gray-400 hover:text-white hover:bg-gray-800\' }`}',
    '      >',
    '        <span>{page.icon}</span>',
    '        <span className="flex-1 truncate">{page.title}</span>',
    '        {/* Context menu trigger */}',
    '        <PageContextMenu page={page} onNewSubpage={onNewSubpage}',
    '          onRename={onRenamePage} onDelete={onDeletePage}',
    '          onSaveTemplate={onSaveAsTemplate} />',
    '      </div>',
    '      {page.children?.map(child => renderPage(child, depth + 1))}',
    '    </div>',
    '  );',
    '',
    '  const tree = buildPageTree(pages);  // Group by parent_page_id',
    '',
    '  return (',
    '    <div className="w-56 bg-gray-900 border-r border-gray-800 flex flex-col h-full">',
    '      <div className="px-4 py-3 border-b border-gray-800">',
    '        <span className="text-xs text-gray-500 font-medium uppercase tracking-wider">Pages</span>',
    '      </div>',
    '      <div className="flex-1 overflow-y-auto py-2 space-y-0.5">',
    '        {tree.map(page => renderPage(page))}',
    '      </div>',
    '      <button onClick={() => onNewPage()}',
    '        className="mx-4 mb-4 py-2 text-sm text-gray-500 hover:text-indigo-400 text-left transition-colors">',
    '        + New Page',
    '      </button>',
    '    </div>',
    '  );',
    '}',
    '',
    '// Utility: flatten pages array into tree by parent_page_id',
    'function buildPageTree(pages) {',
    '  const map = {};',
    '  pages.forEach(p => { map[p.id] = { ...p, children: [] }; });',
    '  const roots = [];',
    '  pages.forEach(p => {',
    '    if (p.parent_page_id) map[p.parent_page_id]?.children.push(map[p.id]);',
    '    else roots.push(map[p.id]);',
    '  });',
    '  return roots;',
    '}',
  ]),
  emptyLine(),

  heading2('6.2 Page Hierarchy API Routes (server/routes/workspace.js — updated)'),
  ...codeBlock([
    '// GET  /api/workspace/:roadmapId/pages      — list all pages for a roadmap',
    '// POST /api/workspace/:roadmapId/pages      — create a new page',
    '// GET  /api/workspace/page/:pageId          — load a single page layout',
    '// PUT  /api/workspace/page/:pageId          — update page layout / title / icon',
    '// DELETE /api/workspace/page/:pageId        — delete page and all subpages',
    '// POST /api/workspace/page/:pageId/template — save page as template',
    '',
    'router.get(\'/:roadmapId/pages\', requireAuth, async (req, res) => {',
    '  const { data } = await supabase',
    '    .from(\'workspace_pages\')',
    '    .select(\'id, title, icon, parent_page_id, sequence_order\')',
    '    .eq(\'roadmap_id\', req.params.roadmapId)',
    '    .eq(\'user_id\', req.user.id)',
    '    .order(\'sequence_order\');',
    '  res.json({ pages: data || [] });',
    '});',
    '',
    'router.post(\'/:roadmapId/pages\', requireAuth, async (req, res) => {',
    '  const { title, parent_page_id, icon } = req.body;',
    '  const { data, error } = await supabase',
    '    .from(\'workspace_pages\')',
    '    .insert({',
    '      roadmap_id: req.params.roadmapId,',
    '      user_id: req.user.id,',
    '      title: title || \'Untitled Page\',',
    '      icon: icon || \'📄\',',
    '      parent_page_id: parent_page_id || null,',
    '      layout_json: [],',
    '    }).select().single();',
    '  if (error) return res.status(500).json({ error: error.message });',
    '  res.json({ page: data });',
    '});',
  ]),
  emptyLine(),
  rule(),

  // ── SECTION 7: FEATURE F — AI ASSISTANT ───────────────────────────────────
  heading1('7. Feature F — Native In-Canvas AI Assistant (Notion AI Style)'),

  heading2('7.1 AIAssistantSidebar Component'),
  ...codeBlock([
    '// client/src/components/workspace/AIAssistantSidebar.jsx',
    '// Copilot trigger: // Collapsible AI chat sidebar with MBTI-aware context, page-scoped',
    '// conversation history, and ability to insert AI output into the Notes block',
    '',
    'export default function AIAssistantSidebar({ isOpen, onClose, pageContext, session, profile }) {',
    '  const [messages, setMessages] = useState([]);',
    '  const [input, setInput] = useState(\'\');',
    '  const [loading, setLoading] = useState(false);',
    '',
    '  const sendMessage = async () => {',
    '    if (!input.trim()) return;',
    '    const userMsg = { role: \'user\', content: input };',
    '    setMessages(prev => [...prev, userMsg]);',
    '    setInput(\'\');',
    '    setLoading(true);',
    '    const { data } = await axios.post(',
    '      `${import.meta.env.VITE_API_URL}/api/ai-assistant`,',
    '      { messages: [...messages, userMsg], pageContext, mbtiType: profile?.mbti_type },',
    '      { headers: { Authorization: `Bearer ${session.access_token}` } }',
    '    );',
    '    setMessages(prev => [...prev, { role: \'assistant\', content: data.reply }]);',
    '    setLoading(false);',
    '  };',
    '',
    '  // Component renders as a slide-in panel from the right',
    '  // pageContext is a serialized summary of the current page\'s blocks and node data',
    '  // Suggested quick prompts shown when messages is empty:',
    '  //   "Summarize my progress on this roadmap"',
    '  //   "What should I study next based on my weak areas?"',
    '  //   "Generate a study note for the active node"',
    '  //   "Recap today\'s session"',
    '}',
  ]),
  emptyLine(),

  heading2('7.2 AI Assistant API Route (server/routes/aiAssistant.js)'),
  ...codeBlock([
    '// POST /api/ai-assistant',
    '// Body: { messages: [], pageContext: string, mbtiType: string }',
    '',
    'router.post(\'/\', requireAuth, async (req, res) => {',
    '  const { messages, pageContext, mbtiType } = req.body;',
    '  const profile = MBTI_AI_PROFILES[mbtiType] || {};',
    '',
    '  const systemPrompt = `',
    '${buildPersonalityContext({ mbti_type: mbtiType })}',
    '',
    'You are an intelligent learning assistant embedded inside the Pulse-Learn workspace.',
    'You have full context of the current page: ${pageContext}',
    '',
    'You can:',
    '- Summarize learning progress, quiz scores, and node completion',
    '- Suggest what to study next based on gaps',
    '- Generate study notes, summaries, and flashcards',
    '- Answer questions about any node topic',
    '',
    'Keep responses concise and calibrated to the learner\'s MBTI cognitive style above.',
    'Format code, lists, and key points with markdown.';`,
    '',
    '  const geminiMessages = messages.map(m => ({',
    '    role: m.role === \'assistant\' ? \'model\' : \'user\',',
    '    parts: [{ text: m.content }],',
    '  }));',
    '',
    '  const model = genAI.getGenerativeModel({ model: \'gemini-1.5-flash\' });',
    '  const chat = model.startChat({ history: geminiMessages.slice(0, -1),',
    '    systemInstruction: systemPrompt });',
    '  const result = await chat.sendMessage(messages.at(-1).content);',
    '',
    '  res.json({ reply: result.response.text() });',
    '});',
  ]),
  emptyLine(),

  heading2('7.3 /ai Slash Command in NotesBlock'),
  ...codeBlock([
    '// In NotesBlock.jsx — extend Tiptap with a custom /ai slash command extension',
    '// Copilot trigger: // Tiptap extension that triggers an AI inline prompt popover when',
    '// user types /ai, sends selected text + prompt to the AI assistant route,',
    '// and inserts the AI response as new content at the cursor position',
    '',
    'const AISlashCommand = Extension.create({',
    '  name: \'aiSlashCommand\',',
    '  addKeyboardShortcuts() {',
    '    return {',
    '      \'/\': () => {',
    '        // Show inline command palette checking if next char completes /ai',
    '        this.editor.commands.openCommandPalette();',
    '        return false;',
    '      },',
    '    };',
    '  },',
    '});',
    '',
    '// When /ai is invoked, show an inline prompt input.',
    '// On submit: POST to /api/ai-assistant with { prompt, context: selected text }',
    '// Insert the response text at the cursor position using editor.commands.insertContent()',
  ]),
  emptyLine(),
  rule(),

  // ── SECTION 8: FEATURE G — RECAP ──────────────────────────────────────────
  heading1('8. Feature G — AI Recap'),

  heading2('8.1 Recap API Route (server/routes/recap.js)'),
  ...codeBlock([
    '// POST /api/recap/:roadmapId',
    '// Generates an MBTI-aware structured summary of all page activity',
    '',
    'router.post(\'/:roadmapId\', requireAuth, async (req, res) => {',
    '  const { pageContext, mbtiType } = req.body;',
    '',
    '  const prompt = `',
    '${buildPersonalityContext({ mbti_type: mbtiType })}',
    '',
    'Generate a Recap for this learning workspace page.',
    'Page data: ${pageContext}',
    '',
    'Return a JSON object:',
    '{',
    '  "headline": "One sentence summary of overall progress",',
    '  "completedNodes": ["node titles completed recently"],',
    '  "weakAreas": ["topics where quiz scores were lowest"],',
    '  "collaboratorActivity": ["what each collaborator contributed"],',
    '  "nextSteps": ["top 3 recommended next actions"],',
    '  "studyTimeToday": "estimated minutes studied today"',
    '}',
    '`;',
    '',
    '  const model = genAI.getGenerativeModel({',
    '    model: \'gemini-1.5-flash\',',
    '    generationConfig: { responseMimeType: \'application/json\' },',
    '  });',
    '  const result = await model.generateContent(prompt);',
    '  const recap = JSON.parse(result.response.text());',
    '  res.json({ recap });',
    '});',
  ]),
  emptyLine(),

  heading2('8.2 RecapBlock Component'),
  ...codeBlock([
    '// client/src/components/workspace/RecapBlock.jsx',
    '// Copilot trigger: // Recap block: shows AI-generated page summary with headline,',
    '// completed nodes list, weak areas, collaborator activity, and next steps.',
    '// Has a Regenerate button that calls /api/recap/:roadmapId',
    '',
    'export default function RecapBlock({ roadmapId, nodes, collaborators, session, profile }) {',
    '  const [recap, setRecap] = useState(null);',
    '  const [loading, setLoading] = useState(false);',
    '',
    '  const generateRecap = async () => {',
    '    setLoading(true);',
    '    const pageContext = JSON.stringify({ nodes, collaborators });',
    '    const { data } = await axios.post(',
    '      `${import.meta.env.VITE_API_URL}/api/recap/${roadmapId}`,',
    '      { pageContext, mbtiType: profile?.mbti_type },',
    '      { headers: { Authorization: `Bearer ${session.access_token}` } }',
    '    );',
    '    setRecap(data.recap);',
    '    setLoading(false);',
    '  };',
    '',
    '  return (/* Render recap.headline, completedNodes, weakAreas, nextSteps */);',
    '}',
  ]),
  emptyLine(),
  rule(),

  // ── SECTION 9: FEATURE H — MCP BRIDGE ─────────────────────────────────────
  heading1('9. Feature H — MCP Bridge Layer'),

  heading2('9.1 MCP Bridge Architecture'),
  para('Following the architecture shown in the Notion MCP diagram (external tools → MCP bridge → workspace), Pulse-Learn\'s MCP Bridge Service acts as an orchestrator that translates workspace events into external tool API calls and imports external data into workspace blocks.'),
  emptyLine(),
  makeTable(
    ['MCP Service', 'Import (→ Workspace)', 'Export (Workspace →)'],
    [
      ['Google Calendar', 'Import upcoming study events as timeline block', 'Create calendar event for node deadlines'],
      ['GitHub', 'Link issues to nodes; show open issue count badge', 'Create issue when quiz fails; close issue on node complete'],
      ['Slack', 'Import channel messages as context to Notes block', 'Post progress, quiz results, completions to channel'],
      ['Notion', 'Pull Notion page content into Notes block', 'Export Recap summary to a Notion page'],
      ['Figma', 'Embed a Figma frame as a reference block', '—'],
    ],
    [1800, 3600, 3960]
  ),
  emptyLine(),

  heading2('9.2 mcpBridgeService.js'),
  ...codeBlock([
    '// server/services/mcpBridgeService.js',
    '// Copilot trigger: // MCP bridge service: routes action requests to the correct',
    '// external service (google_calendar, github, slack, notion, figma) using',
    '// stored OAuth tokens from mcp_connections table',
    '',
    'export async function executeMCPAction(connection, actionType, payload) {',
    '  switch (connection.service) {',
    '    case \'slack\':',
    '      return await postToSlack(connection.connection_config, payload);',
    '    case \'github\':',
    '      return await createGithubIssue(connection.connection_config, payload);',
    '    case \'google_calendar\':',
    '      return await createCalendarEvent(connection.connection_config, payload);',
    '    case \'notion\':',
    '      return await exportToNotion(connection.connection_config, payload);',
    '    default:',
    '      throw new Error(`Unknown MCP service: ${connection.service}`);',
    '  }',
    '}',
    '',
    '// Each sub-function calls the external service\'s API directly.',
    '// Tokens are stored in mcp_connections.connection_config JSONB.',
    '// All functions return { success: true, external_id: string }.',
  ]),
  emptyLine(),

  heading2('9.3 MCPConnectionPanel Component'),
  ...codeBlock([
    '// client/src/components/automation/MCPConnectionPanel.jsx',
    '// Copilot trigger: // Grid of MCP service cards (Google Calendar, GitHub, Slack, Notion, Figma)',
    '// each showing connection status, Connect/Disconnect button, and last sync time',
    '',
    'const MCP_SERVICES = [',
    '  { id: \'google_calendar\', name: \'Google Calendar\', icon: \'📅\', color: \'#4285F4\' },',
    '  { id: \'github\',          name: \'GitHub\',          icon: \'🐙\', color: \'#24292E\' },',
    '  { id: \'slack\',           name: \'Slack\',           icon: \'💬\', color: \'#4A154B\' },',
    '  { id: \'notion\',          name: \'Notion\',          icon: \'📝\', color: \'#000000\' },',
    '  { id: \'figma\',           name: \'Figma\',           icon: \'🎨\', color: \'#F24E1E\' },',
    '];',
    '',
    '// Each card renders: icon, name, status badge (Connected / Not connected),',
    '// Connect button (opens OAuth flow) or Disconnect button',
  ]),
  emptyLine(),
  rule(),

  // ── SECTION 10: FEATURE I — WORKFLOW AUTOMATION ────────────────────────────
  heading1('10. Feature I — Workflow Automation'),

  heading2('10.1 Automation Trigger Registry (client/src/lib/automationTriggers.js)'),
  ...codeBlock([
    '// Full registry of available triggers and actions for the automation rule builder',
    '',
    'export const AUTOMATION_TRIGGERS = {',
    '  node_completed: {',
    '    label: \'A node is marked complete\',',
    '    icon: \'✅\',',
    '    configFields: [{ name: \'node_filter\', type: \'select\', options: [\'any\', \'specific\'] }],',
    '  },',
    '  quiz_failed: {',
    '    label: \'Quiz score falls below threshold\',',
    '    icon: \'❌\',',
    '    configFields: [{ name: \'threshold_pct\', type: \'number\', default: 60 }],',
    '  },',
    '  roadmap_completed: {',
    '    label: \'Roadmap is 100% complete\',',
    '    icon: \'🏆\',',
    '    configFields: [],',
    '  },',
    '  collaborator_joined: {',
    '    label: \'A new collaborator joins the roadmap\',',
    '    icon: \'👋\',',
    '    configFields: [],',
    '  },',
    '};',
    '',
    'export const AUTOMATION_ACTIONS = {',
    '  post_slack: {',
    '    label: \'Post message to Slack\',',
    '    icon: \'💬\',',
    '    requires_service: \'slack\',',
    '    configFields: [',
    '      { name: \'channel\', type: \'text\', placeholder: \'#learning\' },',
    '      { name: \'message_template\', type: \'textarea\',',
    '        placeholder: \'{{user}} completed {{node_title}}!\' },',
    '    ],',
    '  },',
    '  create_github_issue: {',
    '    label: \'Create a GitHub issue\',',
    '    icon: \'🐙\',',
    '    requires_service: \'github\',',
    '    configFields: [',
    '      { name: \'repo\', type: \'text\', placeholder: \'owner/repo\' },',
    '      { name: \'title_template\', type: \'text\', placeholder: \'Review: {{node_title}}\' },',
    '    ],',
    '  },',
    '  create_calendar_event: {',
    '    label: \'Create a Google Calendar event\',',
    '    icon: \'📅\',',
    '    requires_service: \'google_calendar\',',
    '    configFields: [',
    '      { name: \'event_title\', type: \'text\', placeholder: \'Study: {{node_title}}\' },',
    '      { name: \'duration_minutes\', type: \'number\', default: 60 },',
    '    ],',
    '  },',
    '};',
  ]),
  emptyLine(),

  heading2('10.2 Automation Execution (server/routes/automation.js)'),
  ...codeBlock([
    '// Called internally when a workspace event fires.',
    '// POST /api/automation/trigger  — called by node.js verify route and roadmap.js complete route',
    '',
    'router.post(\'/trigger\', requireAuth, async (req, res) => {',
    '  const { roadmap_id, trigger_type, trigger_data } = req.body;',
    '',
    '  // 1. Find all active automation rules for this roadmap and trigger type',
    '  const { data: rules } = await supabase',
    '    .from(\'automation_rules\')',
    '    .select(\'*, mcp_connections(*)\')',
    '    .eq(\'roadmap_id\', roadmap_id)',
    '    .eq(\'trigger_type\', trigger_type)',
    '    .eq(\'is_active\', true);',
    '',
    '  // 2. For each rule, resolve the template vars and call executeMCPAction',
    '  const results = await Promise.allSettled(',
    '    rules.map(rule => {',
    '      const resolvedConfig = resolveTemplateVars(rule.action_config, trigger_data);',
    '      return executeMCPAction(rule.mcp_connections, rule.action_type, resolvedConfig);',
    '    })',
    '  );',
    '',
    '  // 3. Update last_triggered_at',
    '  await supabase.from(\'automation_rules\')',
    '    .update({ last_triggered_at: new Date() })',
    '    .in(\'id\', rules.map(r => r.id));',
    '',
    '  res.json({ triggered: results.length });',
    '});',
    '',
    '// Add trigger calls in existing routes:',
    '// In node.js verify route (after passed = true):',
    '//   await axios.post(\'/api/automation/trigger\', { roadmap_id, trigger_type: \'node_completed\',',
    '//     trigger_data: { node_title, user_name } });',
    '// In roadmap.js complete route:',
    '//   await axios.post(\'/api/automation/trigger\', { roadmap_id, trigger_type: \'roadmap_completed\',',
    '//     trigger_data: { roadmap_title, user_name } });',
  ]),
  emptyLine(),
  rule(),

  // ── SECTION 11: FEATURE J — GLOBAL SEARCH ─────────────────────────────────
  heading1('11. Feature J — Global Search (Cmd+K)'),

  heading2('11.1 GlobalSearch Component'),
  ...codeBlock([
    '// client/src/components/search/GlobalSearch.jsx',
    '// Copilot trigger: // Cmd+K modal with fuzzy search across pages, nodes, notes content.',
    '// Results categorized into Pages, Nodes, Notes, Comments.',
    '// Keyboard navigation with arrow keys and Enter to select.',
    '',
    'export default function GlobalSearch({ session, onNavigate }) {',
    '  const [open, setOpen] = useState(false);',
    '  const [query, setQuery] = useState(\'\');',
    '  const [results, setResults] = useState({ pages: [], nodes: [], notes: [] });',
    '',
    '  useEffect(() => {',
    '    const handler = (e) => {',
    '      if ((e.metaKey || e.ctrlKey) && e.key === \'k\') {',
    '        e.preventDefault();',
    '        setOpen(true);',
    '      }',
    '    };',
    '    window.addEventListener(\'keydown\', handler);',
    '    return () => window.removeEventListener(\'keydown\', handler);',
    '  }, []);',
    '',
    '  useEffect(() => {',
    '    if (!query || query.length < 2) return;',
    '    const timer = setTimeout(async () => {',
    '      const { data } = await axios.get(',
    '        `${import.meta.env.VITE_API_URL}/api/search?q=${encodeURIComponent(query)}`,',
    '        { headers: { Authorization: `Bearer ${session.access_token}` } }',
    '      );',
    '      setResults(data.results);',
    '    }, 200);',
    '    return () => clearTimeout(timer);',
    '  }, [query]);',
    '',
    '  // Renders: full-screen overlay with search input,',
    '  // sections for Pages / Nodes / Notes, keyboard navigation',
    '}',
  ]),
  emptyLine(),

  heading2('11.2 Search API Route (server/routes/search.js)'),
  ...codeBlock([
    '// GET /api/search?q=query',
    '// Uses Supabase full-text search (to_tsvector) across pages, nodes, and active_recall_logs',
    '',
    'router.get(\'/\', requireAuth, async (req, res) => {',
    '  const { q } = req.query;',
    '  if (!q || q.length < 2) return res.json({ results: { pages: [], nodes: [], notes: [] } });',
    '',
    '  const [pages, nodes] = await Promise.all([',
    '    supabase.from(\'workspace_pages\')',
    '      .select(\'id, title, icon, roadmap_id\')',
    '      .eq(\'user_id\', req.user.id)',
    '      .ilike(\'title\', `%${q}%`)',
    '      .limit(5),',
    '    supabase.from(\'nodes\')',
    '      .select(\'id, title, roadmap_id, status\')',
    '      .ilike(\'title\', `%${q}%`)',
    '      .limit(8),',
    '  ]);',
    '',
    '  res.json({',
    '    results: {',
    '      pages: pages.data || [],',
    '      nodes: nodes.data || [],',
    '      notes: [],  // Phase 2: index Tiptap content',
    '    }',
    '  });',
    '});',
  ]),
  emptyLine(),
  rule(),

  // ── SECTION 12: UPDATED API CONTRACT TABLE ─────────────────────────────────
  heading1('12. Full API Contract Table — v4 New Routes'),
  makeTable(
    ['Method', 'Route', 'Body / Params', 'Response'],
    [
      ['GET', '/api/workspace/:roadmapId/pages', '—', '{ pages: [...] }'],
      ['POST', '/api/workspace/:roadmapId/pages', '{ title, parent_page_id, icon }', '{ page }'],
      ['GET', '/api/workspace/page/:pageId', '—', '{ page, layout }'],
      ['PUT', '/api/workspace/page/:pageId', '{ layout, title, icon }', '{ success }'],
      ['DELETE', '/api/workspace/page/:pageId', '—', '{ success }'],
      ['POST', '/api/workspace/page/:pageId/template', '{ template_name }', '{ template_id }'],
      ['POST', '/api/loop-component', '{ roadmap_id, block_type, block_config, title }', '{ component }'],
      ['GET', '/api/loop-component/:id', '—', '{ component }'],
      ['GET', '/api/loop-component/shared/:token', '—', '{ component }'],
      ['PATCH', '/api/loop-component/:id', '{ block_config }', '{ component }'],
      ['POST', '/api/ai-assistant', '{ messages[], pageContext, mbtiType }', '{ reply }'],
      ['POST', '/api/recap/:roadmapId', '{ pageContext, mbtiType }', '{ recap }'],
      ['GET', '/api/search?q=', 'query param', '{ results: { pages, nodes, notes } }'],
      ['GET', '/api/automation/:roadmapId', '—', '{ rules[] }'],
      ['POST', '/api/automation/:roadmapId', '{ trigger_type, action_type, configs }', '{ rule }'],
      ['DELETE', '/api/automation/:ruleId', '—', '{ success }'],
      ['POST', '/api/automation/trigger', '{ roadmap_id, trigger_type, trigger_data }', '{ triggered: n }'],
      ['GET', '/api/mcp/:roadmapId', '—', '{ connections[] }'],
      ['POST', '/api/mcp/:roadmapId', '{ service, connection_config }', '{ connection }'],
      ['DELETE', '/api/mcp/:connectionId', '—', '{ success }'],
    ],
    [900, 2600, 2200, 2660]
  ),
  emptyLine(),
  rule(),

  // ── SECTION 13: UPDATED BLOCK TYPES ───────────────────────────────────────
  heading1('13. Updated blockTypes.js — v4 Additions'),
  ...codeBlock([
    '// Add to BLOCK_TYPES in client/src/lib/blockTypes.js',
    '',
    'LOOP_COMPONENT: {',
    '  id: \'LOOP_COMPONENT\',',
    '  label: \'Loop Component\',',
    '  description: \'Embed a shared live component from another workspace\',',
    '  icon: Share2,  // from lucide-react',
    '  defaultSize: { w: 4, h: 5 },',
    '  minSize: { w: 3, h: 3 },',
    '},',
    'RECAP: {',
    '  id: \'RECAP\',',
    '  label: \'AI Recap\',',
    '  description: \'AI-generated summary of this page and workspace\',',
    '  icon: Sparkles,',
    '  defaultSize: { w: 4, h: 5 },',
    '  minSize: { w: 3, h: 4 },',
    '},',
    'AI_CHAT: {',
    '  id: \'AI_CHAT\',',
    '  label: \'AI Assistant\',',
    '  description: \'Inline AI chat with full workspace context\',',
    '  icon: Bot,',
    '  defaultSize: { w: 3, h: 7 },',
    '  minSize: { w: 3, h: 5 },',
    '},',
  ]),
  emptyLine(),
  rule(),

  // ── SECTION 14: EDGE CASES ─────────────────────────────────────────────────
  heading1('14. Edge Cases & Mitigations — v4'),
  emptyLine(),
  makeTable(
    ['Edge Case', 'Problem', 'Mitigation'],
    [
      ['Loop Component circular embed', 'Component A is embedded in Page B, which is embedded in Component A', 'Track embed depth; block embed if component_id already appears in the parent chain'],
      ['MCP token expiry', 'OAuth tokens for Slack/GitHub expire mid-session', 'Catch 401 from external service → set mcp_connections.is_active = false → notify user in MCPConnectionPanel'],
      ['Automation infinite loop', 'Completing a node triggers Slack, which triggers a webhook that triggers another completion', 'Add a minimum 60-second cooldown per automation rule per trigger event'],
      ['Page hierarchy depth', 'Users create 10+ levels of nested subpages', 'Hard-cap at 3 nesting levels in the UI; server validates parent depth before INSERT'],
      ['Global search performance', 'ILIKE on large nodes table causes slow queries', 'Add GIN index on nodes.title and workspace_pages.title; add pg_trgm extension for fuzzy matching'],
      ['AI Assistant context too large', 'pageContext with 50+ nodes exceeds Gemini context window', 'Truncate pageContext to the 10 most recently active nodes + current page notes only'],
      ['Loop Component public share security', 'Anyone with the share token can access a public component', 'Token is 16-char random — effectively unguessable. Add optional password protection as post-v4 feature'],
    ],
    [2100, 3000, 4260]
  ),
  emptyLine(),
  rule(),

  // ── SECTION 15: INSTALLATION ───────────────────────────────────────────────
  heading1('15. New npm Dependencies — v4'),
  emptyLine(),
  makeTable(
    ['Package', 'Side', 'Why'],
    [
      ['@slack/web-api', 'server', 'Post messages to Slack channels via Slack Web API'],
      ['@octokit/rest', 'server', 'Create/update GitHub issues via GitHub REST API'],
      ['googleapis', 'server', 'Create Google Calendar events via Google API Node client'],
      ['fuse.js', 'client', 'Fuzzy search for client-side instant search filtering in GlobalSearch'],
      ['@tiptap/extension-slash-commands', 'client', 'Tiptap extension for /command palette in NotesBlock'],
    ],
    [2500, 1200, 5660]
  ),
  emptyLine(),
  ...codeBlock([
    '# Server',
    'cd server && npm install @slack/web-api @octokit/rest googleapis',
    '',
    '# Client',
    'cd client && npm install fuse.js @tiptap/extension-slash-commands',
  ]),
  emptyLine(),
  rule(),

  // ── SECTION 16: DEPLOYMENT CHECKLIST ──────────────────────────────────────
  heading1('16. Deployment Checklist — v4 Additions'),
  emptyLine(),
  bullet('Run v4 SQL in Supabase: workspace_pages, loop_components, loop_component_embeds, mcp_connections, automation_rules'),
  bullet('Add Supabase Realtime publication for loop_components and workspace_pages'),
  bullet('Add GIN index on nodes.title for search performance: CREATE INDEX nodes_title_gin ON nodes USING gin(to_tsvector(\'english\', title));'),
  bullet('Add pg_trgm extension: CREATE EXTENSION IF NOT EXISTS pg_trgm;'),
  bullet('Configure OAuth app credentials for Slack, GitHub, Google Calendar in server .env'),
  bullet('Add new env vars: SLACK_CLIENT_ID, SLACK_CLIENT_SECRET, GITHUB_APP_ID, GITHUB_APP_SECRET, GOOGLE_OAUTH_CLIENT_ID, GOOGLE_OAUTH_CLIENT_SECRET'),
  bullet('Register new backend routes in server/index.js: loopComponent, search, recap, aiAssistant, automation, mcp'),
  bullet('Test Loop Component detach → share link → embed in second page → data sync'),
  bullet('Test automation: complete a node → verify Slack message fires (if connected)'),
  bullet('Test Cmd+K global search across pages and nodes'),
  bullet('Test AI Recap generation for a roadmap with 5+ completed nodes'),
  emptyLine(),
  rule(),

  // ── SECTION 17: COPILOT CHEATSHEET ────────────────────────────────────────
  heading1('17. GitHub Copilot Prompt Cheatsheet — v4 New Files'),
  emptyLine(),
  makeTable(
    ['File', 'Opening Trigger Comment for Copilot'],
    [
      ['client/src/components/workspace/PageSidebar.jsx', '// Collapsible sidebar with nested page tree, drag to reorder, right-click context menu: New subpage, Open, Share, Rename and style, Recap, Duplicate, Add to workspace, Save as template, Delete'],
      ['client/src/components/workspace/AIAssistantSidebar.jsx', '// Slide-in AI chat sidebar with MBTI-aware context, page-scoped conversation history, quick prompt suggestions, and Insert to Notes button'],
      ['client/src/components/workspace/RecapBlock.jsx', '// AI Recap block: shows structured summary with headline, completed nodes, weak areas, collaborator activity, next steps. Has Regenerate button that calls /api/recap/:roadmapId'],
      ['client/src/components/workspace/LoopComponentViewer.jsx', '// Renders a Loop Component embed: fetches component by ID, shows block header with source workspace name and live sync indicator, renders the underlying block component'],
      ['client/src/components/search/GlobalSearch.jsx', '// Cmd+K global search modal: fuzzy search across pages, nodes, notes. Results in categories with keyboard navigation (arrow keys + Enter). Recent searches stored in sessionStorage'],
      ['client/src/components/automation/AutomationRuleBuilder.jsx', '// No-code automation rule builder: select trigger from AUTOMATION_TRIGGERS, select action from AUTOMATION_ACTIONS filtered by connected MCP services, configure template vars'],
      ['client/src/components/automation/MCPConnectionPanel.jsx', '// Grid of MCP service cards (Google Calendar, GitHub, Slack, Notion, Figma) each with status badge, Connect/Disconnect button, last synced time'],
      ['client/src/hooks/useLoopComponents.js', '// Custom hook: fetch loop components for a roadmap, detach block as component, get share link, subscribe to Realtime updates for live sync across embeds'],
      ['client/src/hooks/useAIAssistant.js', '// Custom hook: manage AI assistant chat state, send message to /api/ai-assistant with pageContext and MBTI type, maintain conversation history per page'],
      ['server/routes/loopComponent.js', '// Express routes: POST create Loop Component, GET fetch by ID, GET fetch by share token (no auth), PATCH update config — upserts to loop_components table'],
      ['server/routes/recap.js', '// Express route: POST /api/recap/:roadmapId — builds MBTI-aware Gemini prompt with page context, returns structured JSON recap with headline, completed nodes, weak areas, next steps'],
      ['server/routes/aiAssistant.js', '// Express route: POST /api/ai-assistant — multi-turn Gemini chat with MBTI personality context and serialized page context injected as system prompt'],
      ['server/routes/search.js', '// Express route: GET /api/search?q= — searches workspace_pages.title and nodes.title with ILIKE, returns categorized results with page/node/notes buckets'],
      ['server/routes/automation.js', '// Express routes: CRUD for automation_rules, POST /trigger endpoint that finds matching active rules for a roadmap + trigger_type and calls executeMCPAction'],
      ['server/services/mcpBridgeService.js', '// MCP bridge service: routes action_type to correct external API (slack, github, google_calendar, notion, figma), resolves template vars like {{node_title}} and {{user_name}}'],
    ],
    [3200, 6160]
  ),
  emptyLine(),
  rule(),

  new Paragraph({
    alignment: AlignmentType.CENTER,
    spacing: { before: 240, after: 120 },
    children: [new TextRun({ text: 'PRD Version 4.0 — Pulse-Learn AI', size: 18, font: 'Arial', color: '6B7280', italics: true })],
  }),
  new Paragraph({
    alignment: AlignmentType.CENTER,
    spacing: { before: 40, after: 40 },
    children: [new TextRun({ text: 'Adds: Loop Components · Page Hierarchy · Native AI Assistant · AI Recap · MCP Bridge · Workflow Automation · Global Search', size: 16, font: 'Arial', color: '9CA3AF', italics: true })],
  }),
  new Paragraph({
    alignment: AlignmentType.CENTER,
    spacing: { before: 40, after: 40 },
    children: [new TextRun({ text: 'Cumulative: Full Auth · MBTI Engine · Block Workspace · Analytics · Collaboration · Blockchain Credentials', size: 16, font: 'Arial', color: '9CA3AF', italics: true })],
  }),
];

// ─── BUILD DOCUMENT ──────────────────────────────────────────────────────────
const doc = new Document({
  numbering: {
    config: [
      {
        reference: 'bullets',
        levels: [{
          level: 0, format: LevelFormat.BULLET, text: '•',
          alignment: AlignmentType.LEFT,
          style: { paragraph: { indent: { left: 480, hanging: 240 } } },
        }, {
          level: 1, format: LevelFormat.BULLET, text: '◦',
          alignment: AlignmentType.LEFT,
          style: { paragraph: { indent: { left: 720, hanging: 240 } } },
        }],
      },
      {
        reference: 'numbers',
        levels: [{
          level: 0, format: LevelFormat.DECIMAL, text: '%1.',
          alignment: AlignmentType.LEFT,
          style: { paragraph: { indent: { left: 480, hanging: 240 } } },
        }],
      },
    ],
  },
  styles: {
    default: {
      document: { run: { font: 'Arial', size: 20, color: '374151' } },
    },
    paragraphStyles: [
      {
        id: 'Heading1', name: 'Heading 1', basedOn: 'Normal', next: 'Normal', quickFormat: true,
        run: { size: 32, bold: true, font: 'Arial', color: '1E1B4B' },
        paragraph: { spacing: { before: 400, after: 120 }, outlineLevel: 0 },
      },
      {
        id: 'Heading2', name: 'Heading 2', basedOn: 'Normal', next: 'Normal', quickFormat: true,
        run: { size: 26, bold: true, font: 'Arial', color: '312E81' },
        paragraph: { spacing: { before: 280, after: 80 }, outlineLevel: 1 },
      },
      {
        id: 'Heading3', name: 'Heading 3', basedOn: 'Normal', next: 'Normal', quickFormat: true,
        run: { size: 22, bold: true, font: 'Arial', color: '4F46E5' },
        paragraph: { spacing: { before: 200, after: 60 }, outlineLevel: 2 },
      },
    ],
  },
  sections: [{
    properties: {
      page: {
        size: { width: 12240, height: 15840 },
        margin: { top: 1080, right: 1080, bottom: 1080, left: 1080 },
      },
    },
    children,
  }],
});

Packer.toBuffer(doc).then((buffer) => {
  fs.writeFileSync('/mnt/user-data/outputs/Pulse-Learn-PRD-v4.docx', buffer);
  console.log('Done!');
});
